server:
  port: 9080
log:
  directory: /opt/logappli
  server: 192.168.0.10
  login: jeremy
  password: galaxxie
  fichierPattern: omega-supervision\.log\.\d{4}-\d{2}-\d{2}

#same port for metrics
management:
 port: 9080

spring:
 profiles: default
 application:
  name: supervision-chart
 datasource:
  url: jdbc:hsqldb:mem:supervision-chart
  username: sa
  password:
  driverClassName: org.hsqldb.jdbcDriver
#use for p6spy logs : driverClassName: com.p6spy.engine.spy.P6SpyDriver 

 jpa:
  database: HSQL
  show-sql: false
  hibernate:
   ddl-auto: create-drop
   dialect: org.hibernate.dialect.HSQLDialect

---

spring:
 profiles: production
 datasource:
  url: jdbc:mysql://localhost/supervision-chart
  username: supervision
  driverClassName: com.mysql.jdbc.Driver
 jpa:
  database: MYSQL
  show-sql: false
  hibernate:
   ddl-auto: create-drop
   dialect: org.hibernate.dialect.MySQL5Dialect
   naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
